In [3]:
import collections
import preprocessing.utils.preprocessing_utils
import estimation.utils.estimation_utils
import matplotlib.pyplot as plt
from itertools import combinations
from scipy.sparse import random
from random import choice
import numpy as np

# Test get_donor_tensor method
Design of get_donor_tensor method:
- brute force: iterate over all possible combinations of units
- for each combination of units, calculate number of overalapping timestamps
- find the set of units and timestamps with the largest min(num_donor_units, num_overlapping_timestamps)

In [4]:
from importlib import reload
estimation.utils.estimation_utils = reload(estimation.utils.estimation_utils)
# prepare example 1
num_units = 5
num_times = 3
num_interventions = 2
num_outcomes = 1
tensor = (random(num_units*num_times*num_interventions*num_outcomes, 1, density=0.9, random_state=0).A.\
           reshape(num_units, num_times, num_interventions, num_outcomes)*100).astype('int8').astype('f')
tensor[tensor == 0] = np.nan
print("------Original tensor------")
print(tensor)

# print out for sanity check
unit = 1
time = 0
intervention = 0
outcome = 0
tensor[unit, time, intervention, outcome] = np.nan
print("------Sanity check printout------")
print("Unit: %d  Time: %d  Intervention: %d  Outcome: %d" % (unit, time, intervention, outcome))
print("Missing value: (%d, %d)" % (unit, time*num_interventions + intervention))
print(tensor[:, :, :, outcome].reshape(num_units, -1))


# find donor tensor
estimation.utils.estimation_utils.get_donor_tensor(tensor[:, :, :, outcome], unit, time, intervention)

------Original tensor------
[[[[65.]
   [32.]]

  [[14.]
   [96.]]

  [[38.]
   [10.]]]


 [[[22.]
   [90.]]

  [[18.]
   [61.]]

  [[80.]
   [58.]]]


 [[[nan]
   [47.]]

  [[73.]
   [nan]]

  [[47.]
   [53.]]]


 [[[90.]
   [44.]]

  [[13.]
   [nan]]

  [[75.]
   [21.]]]


 [[[67.]
   [ 9.]]

  [[52.]
   [72.]]

  [[87.]
   [14.]]]]
------Sanity check printout------
Unit: 1  Time: 0  Intervention: 0  Outcome: 0
Missing value: (1, 0)
[[65. 32. 14. 96. 38. 10.]
 [nan 90. 18. 61. 80. 58.]
 [nan 47. 73. nan 47. 53.]
 [90. 44. 13. nan 75. 21.]
 [67.  9. 52. 72. 87. 14.]]
(0, 3, 4) [1 2 4 5]
X train shape: (3, 4)
y train shape: (4,)
X test shape: (3, 1)
Donor units: (0, 3, 4)
Overlapping measurements of donor units: [1 2 4 5]


(array([[32., 14., 38., 10.],
        [44., 13., 75., 21.],
        [ 9., 52., 87., 14.]], dtype=float32),
 array([90., 18., 80., 58.], dtype=float32),
 array([[65.],
        [90.],
        [67.]], dtype=float32))

In [5]:
# prepare example 2
num_units = 4
num_times = 6
num_interventions = 2
num_outcomes = 1
tensor = (random(num_units*num_times*num_interventions*num_outcomes, 1, density=0.9, random_state=0).A.\
           reshape(num_units, num_times, num_interventions, num_outcomes)*100).astype('int8').astype('f')
tensor[tensor == 0] = np.nan
print("------Original tensor------")
print(tensor)

# print out for sanity check
unit = 2
time = 4
intervention = 1
outcome = 0
tensor[unit, time, intervention, outcome] = np.nan
print("------Sanity check printout------")
print("Unit: %d  Time: %d  Intervention: %d  Outcome: %d" % (unit, time, intervention, outcome))
print("Missing value: (%d, %d)" % (unit, time*num_interventions + intervention))
print(tensor[:, :, :, outcome].reshape(num_units, -1))


# find donor tensor
estimation.utils.estimation_utils.get_donor_tensor(tensor[:, :, :, outcome], unit, time, intervention)

------Original tensor------
[[[[nan]
   [67.]]

  [[96.]
   [nan]]

  [[47.]
   [58.]]

  [[66.]
   [22.]]

  [[65.]
   [87.]]

  [[38.]
   [90.]]]


 [[[31.]
   [63.]]

  [[62.]
   [35.]]

  [[32.]
   [41.]]

  [[17.]
   [97.]]

  [[63.]
   [67.]]

  [[60.]
   [ 1.]]]


 [[[94.]
   [99.]]

  [[18.]
   [90.]]

  [[75.]
   [10.]]

  [[73.]
   [44.]]

  [[21.]
   [61.]]

  [[32.]
   [47.]]]


 [[[62.]
   [13.]]

  [[33.]
   [nan]]

  [[14.]
   [ 3.]]

  [[95.]
   [77.]]

  [[nan]
   [nan]]

  [[65.]
   [ 9.]]]]
------Sanity check printout------
Unit: 2  Time: 4  Intervention: 1  Outcome: 0
Missing value: (2, 9)
[[nan 67. 96. nan 47. 58. 66. 22. 65. 87. 38. 90.]
 [31. 63. 62. 35. 32. 41. 17. 97. 63. 67. 60.  1.]
 [94. 99. 18. 90. 75. 10. 73. 44. 21. nan 32. 47.]
 [62. 13. 33. nan 14.  3. 95. 77. nan nan 65.  9.]]
(0, 1) [ 1  2  4  5  6  7  8 10 11]
X train shape: (2, 9)
y train shape: (9,)
X test shape: (2, 1)
Donor units: (0, 1)
Overlapping measurements of donor units: [ 1  2  4  5  6  7

(array([[67., 96., 47., 58., 66., 22., 65., 38., 90.],
        [63., 62., 32., 41., 17., 97., 63., 60.,  1.]], dtype=float32),
 array([99., 18., 75., 10., 73., 44., 21., 32., 47.], dtype=float32),
 array([[87.],
        [67.]], dtype=float32))

In [6]:
# prepare example 3
num_units = 10
num_times = 3
num_interventions = 4
num_outcomes = 2
tensor = (random(num_units*num_times*num_interventions*num_outcomes, 1, density=0.8, random_state=0).A.\
           reshape(num_units, num_times, num_interventions, num_outcomes)*100).astype('int8').astype('f')
tensor[tensor == 0] = np.nan
print("------Original tensor------")
print(tensor)

# print out for sanity check
unit = 6
time = 1
intervention = 0
outcome = 0
tensor[unit, time, intervention, outcome] = np.nan
print("------Sanity check printout------")
print("Unit: %d  Time: %d  Intervention: %d  Outcome: %d" % (unit, time, intervention, outcome))
print("Missing value: (%d, %d)" % (unit, time*num_interventions + intervention))
print(tensor[:, :, :, outcome].reshape(num_units, -1))


# find donor tensor
estimation.utils.estimation_utils.get_donor_tensor(tensor[:, :, :, outcome], unit, time, intervention)

------Original tensor------
[[[[86. 18.]
   [29. 51.]
   [25. 93.]
   [ 8. 45.]]

  [[ 3. nan]
   [98. 26.]
   [73. 11.]
   [58.  6.]]

  [[68. 37.]
   [17. 94.]
   [87. nan]
   [61. 13.]]]


 [[[71. nan]
   [37.  6.]
   [ 7. nan]
   [39. 64.]]

  [[nan 75.]
   [79. 69.]
   [nan 72.]
   [58. nan]]

  [[86. 28.]
   [69. 34.]
   [20. 69.]
   [96. nan]]]


 [[[33. 77.]
   [48. 58.]
   [20. 37.]
   [90. 39.]]

  [[14. 28.]
   [nan 84.]
   [18. 51.]
   [63. 99.]]

  [[ 5. 37.]
   [42. nan]
   [67. 90.]
   [nan 45.]]]


 [[[nan 73.]
   [86. 62.]
   [52. nan]
   [72. nan]]

  [[55. nan]
   [nan 19.]
   [24.  8.]
   [10. nan]]

  [[nan 57.]
   [27.  5.]
   [43. 18.]
   [97. 96.]]]


 [[[ 2. 58.]
   [13. nan]
   [ 1. 16.]
   [68. nan]]

  [[67. 77.]
   [ 2. 21.]
   [97. 69.]
   [53. 92.]]

  [[63.  9.]
   [30. nan]
   [58. nan]
   [49. 45.]]]


 [[[78. 42.]
   [23. 78.]
   [24. 94.]
   [ 1. nan]]

  [[ 4. 94.]
   [48. 77.]
   [77. 27.]
   [22. 92.]]

  [[35. 47.]
   [94. 26.]
   [nan 23.]
   [n

(array([[29.,  8., 73., 58., 17.],
        [48., 90., 18., 63., 42.],
        [86., 72., 24., 10., 27.],
        [13., 68., 97., 53., 30.],
        [23.,  1., 77., 22., 94.]], dtype=float32),
 array([61., 82.,  1., 38., 27.], dtype=float32),
 array([[ 3.],
        [14.],
        [55.],
        [67.],
        [ 4.]], dtype=float32))

# Synthetic intervention estimation example
1. initiate a SyntheticIntervention class and set up the threshold and rho
2. fit mode with tensor data from preprocessing step
3. predict targets of interest
4. enter title name and plot spectrum

Subspace inclusion test: if more than rho fraction of the spectral energy of testing left singular vectors lies outside the span of training left singular vectors, test failed

For each target to be predicted, print out stats of donor matrix, donor units, overlapping timestamps, if subspace inclusion test passed, the outcome and 95% confidence interval